const fs = require('node:fs');
const path = require('node:path');
const { createHash } = require('node:crypto');
const root = path.resolve(__dirname, '../..');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'artifacts/SkillArtwork/Manifest.json'), 'utf8'));
const ready = manifest.skills.filter(skill => fs.existsSync(path.join(root, skill.asset)) && fs.existsSync(path.join(root, 'artifacts/SkillArtwork/Records', `${skill.id}.json`)));
const missing = manifest.skills.filter(skill => !ready.includes(skill));
if (missing.length && !process.argv.includes('--partial')) throw new Error(`Missing ${missing.length} artworks: ${missing.map(skill => skill.id).join(', ')}`);
const hash = createHash('sha256');
for (const skill of ready) hash.update(skill.type).update(fs.readFileSync(path.join(root, skill.asset)));
const revision = hash.digest('hex').slice(0, 16);
const source = '// Generated by tools/SkillArtwork/BuildRuntimeCatalog.cjs.\n' +
  `var/nexus_skill_artwork_revision = "${revision}"\nvar/list/nexus_skill_artwork_files = list(\n` +
  ready.map(skill => `\t"${skill.type}" = '${skill.asset}'`).join(',\n') + '\n)\n';
const file = path.join(root, 'src/Code/UI/SkillArtworkCatalog.dm');
if (process.argv.includes('--check')) {
  if (fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n') !== source) throw new Error('Runtime artwork catalog is stale.');
} else fs.writeFileSync(file, source);
console.log(`Runtime artwork catalog: ${ready.length}/${manifest.skills.length}, revision ${revision}.`);
