// Z-Level Settings -----------------------------------

var/const
	Z_LEVEL_EARTH = 1
	Z_LEVEL_KAMI_OUTPOST_AND_CAVES = 2
	Z_LEVEL_Namekian = 3
	Z_LEVEL_BRAAL = 4
	Z_LEVEL_CHECKPOINT = 5
	Z_LEVEL_HELL = 6
	Z_LEVEL_HEAVEN = 7
	Z_LEVEL_ARCONIA = 8
	Z_LEVEL_SSX = 9
	Z_LEVEL_HBTC = 10
	Z_LEVEL_ATLANTIS_SHIP_GOD_AREA = 11
	Z_LEVEL_ICE = 12
	Z_LEVEL_KAIOSHIN = 13
	Z_LEVEL_DESERT_JUNGLE_ANDROID = 14
	Z_LEVEL_SONKU = 15
	Z_LEVEL_SPACE = 16
	Z_LEVEL_PRISON = 17
	Z_LEVEL_CORE = 18
	Z_LEVEL_BATTLEGROUNDS = 19

var/const
	LETHAL_COMBAT 						= "Fight to Death"
	CASUAL_COMBAT 						= "Casual Spar" 
