var/const/SKILL_CATEGORY_RUSH = "Rush"
var/const/SKILL_CATEGORY_BLAST = "Blast"
var/const/SKILL_CATEGORY_BIG_BLAST = "Big Blast"
var/const/SKILL_CATEGORY_CONTROLLED_BLAST = "Controlled Blast"
var/const/SKILL_CATEGORY_CONTROLLED_BIG_BLAST = "Controlled Big Blast"
var/const/SKILL_CATEGORY_BEAM = "Beam"
var/const/SKILL_CATEGORY_EVASIVE = "Evasive"
var/const/SKILL_CATEGORY_UTILITY = "Utility"

var/list/SKILL_CATEGORIES = list(
	SKILL_CATEGORY_RUSH,
	SKILL_CATEGORY_BLAST,
	SKILL_CATEGORY_BIG_BLAST,
	SKILL_CATEGORY_CONTROLLED_BLAST,
	SKILL_CATEGORY_CONTROLLED_BIG_BLAST,
	SKILL_CATEGORY_BEAM,
	SKILL_CATEGORY_EVASIVE,
	SKILL_CATEGORY_UTILITY
)
