// Extract explicit native verb categories/names; runtime membership still authorizes commands.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const dme = fs.readFileSync(path.join(root, 'DU.dme'), 'utf8');
const catalog = {};
for (const include of dme.matchAll(/^#include "([^"]+\.dm)"/gm)) {
  const filename = include[1].replaceAll('\\', '/');
  if (filename.endsWith('ClassicCommandCatalog.dm')) continue;
  const source = fs.readFileSync(path.join(root, filename), 'utf8');
  let block = false, multiline = false, devDepth = 0, stack = [], active = null;
  function finish() {
    if (active && active.path.includes('/verb/') && !active.hidden && !active.name.startsWith('.'))
      catalog[active.path] = {name:active.name, category:active.category, explicitSource:active.explicitSource};
    active = null;
  }
  for (const raw of source.split(/\r?\n/)) {
    // Default DU.dme does not compile the optional developer-only command blocks.
    if(/^\s*#ifdef\s+NEXUS_DEV_TOOLS\b/.test(raw)){finish();devDepth=1;continue;}
    if(devDepth){if(/^\s*#if/.test(raw))devDepth++;if(/^\s*#endif/.test(raw))devDepth--;continue;}
    if(multiline){if(raw.includes('"}'))multiline=false;continue;}
    if(/(?:=|return)\s*\{"/.test(raw)&&!raw.slice(raw.indexOf('{"')+2).includes('"}')){multiline=true;continue;}
    // Remove comments without treating comment markers inside quoted strings as code.
    let line='', quote=false, escape=false;
    for(let i=0;i<raw.length;i++) {
      const a=raw[i], b=raw[i+1];
      if(block){if(a==='*'&&b==='/'){block=false;i++;}continue;}
      if(!quote&&a==='/'&&b==='*'){block=true;i++;continue;}
      if(!quote&&a==='/'&&b==='/')break;
      line+=a;
      if(a==='"'&&!escape)quote=!quote;
      escape=a==='\\'&&!escape;
    }
    const text=line.trim();if(!text)continue;
    const indent=line.match(/^\s*/)[0].replaceAll('\t','    ').length;
    if(active && indent<=active.indent)finish();
    if(active) {
      const sourceSetting=text.match(/^set\s+src\s*(=|in\b)/);
      if(sourceSetting)active.explicitSource=sourceSetting[1]!=='=';
      const setting=text.match(/^set\s+(name|category|hidden|invisibility)\s*=\s*(.*)/);
      if(setting){const [,key,val]=setting;if(key==='hidden'&&/^(1|TRUE)\b/.test(val))active.hidden=true;
        if(key==='invisibility'&&!/^(0|FALSE)\b/.test(val))active.hidden=true;
        if(key==='category'&&/^null\b/.test(val))active.category=null;
        const str=val.match(/^"([^"\n]*)"/);if(str&&(key==='category'||key==='name'))active[key]=str[1];}
      continue;
    }
    while(stack.length&&stack.at(-1).indent>=indent)stack.pop();
    const decl=text.match(/^(\/?[A-Za-z_][\w/]*)(\s*\(|\s*$)/);
    if(!decl)continue;
    const part=decl[1], parent=stack.length?stack.at(-1).path:'';
    const full=(part.startsWith('/')?part:parent+'/'+part).replace(/\/$/,'');
    if(decl[2].includes('('))active={path:full,indent,name:full.split('/').at(-1).replaceAll('_',' '),category:'Commands',hidden:false,explicitSource:full.startsWith('/obj/')};
    else stack.push({indent,path:full});
  }
  finish();
}
const output='// Generated by tools/BuildClassicCommandCatalog.cjs. Name, category, explicit source argument.\nvar/list/nexus_classic_command_catalog = list(\n'+Object.entries(catalog).sort(([a],[b])=>a.localeCompare(b)).map(([key,v])=>'\t'+JSON.stringify(key)+' = list('+JSON.stringify(v.name)+', '+JSON.stringify(v.category)+', '+(v.explicitSource?'TRUE':'FALSE')+')').join(',\n')+'\n)\n';
const target=path.join(root,'src/Code/UI/ClassicCommandCatalog.dm');
if(process.argv.includes('--check')){if(fs.readFileSync(target,'utf8').replace(/\r\n/g,'\n')!==output.replace(/\r\n/g,'\n'))throw Error('Classic command catalog is stale; run node tools/BuildClassicCommandCatalog.cjs');}
else fs.writeFileSync(target,output);
console.log(`Classic command catalog: ${Object.keys(catalog).length} visible command/context verbs`);
