proc/runViltrumSliceStartupSmokeTests()
	runViltrumCapitalStartupSmokeTests()
	var/turf/structure = locate(219, 263, Z_LEVEL_VILTRUM)
	nexusSmokeAssert(istype(structure, /turf/ViltrumRoof) && structure.density && structure.opacity, "Viltrum roofs must be the solid sight-blocking walls")
	var/mob/NexusSmokeTest/roof_probe = new(locate(218,263,Z_LEVEL_VILTRUM))
	nexusSmokeAssert(!structure.Enter(roof_probe), "Viltrum structural roof allows walking through it")
	roof_probe.Flying = TRUE
	nexusSmokeAssert(!structure.Enter(roof_probe), "Viltrum structural roof allows the generic flying bypass")
	roof_probe.KB = TRUE
	nexusSmokeAssert(!structure.Enter(roof_probe), "Viltrum structural roof allows knockback through it")
	del(roof_probe)
	var/turf/facade = locate(219, 262, Z_LEVEL_VILTRUM)
	nexusSmokeAssert(istype(facade, /turf/ViltrumWall) && !facade.density && !facade.opacity, "Viltrum wall faces must remain decorative")
	var/turf/reading_position = locate(223, 267, Z_LEVEL_VILTRUM)
	var/obj/ViltrumFurnishing/ArchiveTable/reading_table = locate() in reading_position
	nexusSmokeAssert(istype(reading_position, /turf/ViltrumFloor) && reading_table, "Viltrum furniture must preserve its underlying floor")
	if(reading_table)
		var/icon/table_art = icon(reading_table.icon, reading_table.icon_state)
		nexusSmokeAssert(table_art.Width() == 32 && table_art.Height() == 32 && !table_art.GetPixel(1, 32), "Viltrum furnishings require a transparent 32x32 frame")
	for(var/tile_x = 240, tile_x <= 260, tile_x++)
		for(var/tile_y = 68, tile_y <= 88, tile_y++)
			var/turf/arrival = locate(tile_x, tile_y, Z_LEVEL_VILTRUM)
			nexusSmokeAssert(arrival && !arrival.density && istype(arrival.loc, /area/Viltrum), "Viltrum arrival scatter contains dense or missing terrain")
			if(arrival)
				for(var/atom/movable/occupant in arrival)
					nexusSmokeAssert(!occupant.density, "Viltrum arrival scatter contains a dense object")
	var/turf/forum = locate(250, 250, Z_LEVEL_VILTRUM)
	nexusSmokeAssert(istype(forum, /turf/ViltrumFloor) && !forum.density, "Viltrum forum spawn is not on civic flooring")
	var/turf/regulator_position = locate(270, 284, Z_LEVEL_VILTRUM)
	var/obj/ViltrumConsole/Reactor/regulator = locate() in regulator_position
	nexusSmokeAssert(regulator && regulator.density && !regulator.opacity, "Viltrum energy landmark is missing or has unexpected collision")
	for(var/tile_x = 232, tile_x <= 269, tile_x++)
		for(var/tile_y = 219, tile_y <= 248, tile_y++)
			var/turf/combat_floor = locate(tile_x, tile_y, Z_LEVEL_VILTRUM)
			nexusSmokeAssert(combat_floor && !combat_floor.density, "Viltrum combat forum is obstructed")
			if(combat_floor)
				for(var/atom/movable/occupant in combat_floor)
					nexusSmokeAssert(!occupant.density, "Viltrum combat forum contains a dense object")

proc/runViltrumCapitalStartupSmokeTests()
	runViltrumBoundaryStartupSmokeTests()
	runViltrumDoorStartupSmokeTests()
	for(var/list/field in list(list(25,225,74,274), list(136,236,164,264), list(326,221,373,268)))
		for(var/tile_x = field[1], tile_x <= field[3], tile_x++)
			for(var/tile_y = field[2], tile_y <= field[4], tile_y++)
				var/turf/combat_floor = locate(tile_x, tile_y, Z_LEVEL_VILTRUM)
				nexusSmokeAssert(combat_floor && !combat_floor.density, "Viltrum capital combat terrain is obstructed")
				if(combat_floor)
					for(var/atom/movable/occupant in combat_floor)
						nexusSmokeAssert(!occupant.density, "Viltrum capital combat floor contains a dense object")
	for(var/list/exit_point in list(list(350,214), list(350,276), list(316,245), list(384,245)))
		var/turf/arena_exit = locate(exit_point[1], exit_point[2], Z_LEVEL_VILTRUM)
		nexusSmokeAssert(arena_exit && !arena_exit.density, "Viltrum arena exit is blocked")
	var/turf/throne_position = locate(10, 12, Z_LEVEL_CITY_INTERIORS)
	var/obj/ViltrumCapitalFurnishing/Throne/throne = locate() in throne_position
	nexusSmokeAssert(throne && istype(throne_position, /turf/ViltrumFloor), "Viltrum palace throne or independent floor is missing")
	for(var/state_name in list("bed", "medical_bed", "locker", "freight_crate", "throne", "serving_counter", "workbench", "communications_mast"))
		var/icon/furniture_art = icon('src/Icons/Turfs/Viltrum/ViltrumCapitalObjects.dmi', state_name)
		nexusSmokeAssert(furniture_art.Width() == 32 && furniture_art.Height() == 32 && !furniture_art.GetPixel(1,32), "Viltrum capital furnishing requires transparent 32x32 art")

proc/runViltrumBoundaryStartupSmokeTests()
	var/turf/landing = locate(VILTRUM_LANDING_X,VILTRUM_LANDING_Y,Z_LEVEL_VILTRUM)
	var/mob/NexusSmokeTest/boundary_probe = new(landing)
	for(var/list/edge in list(list(1,1),list(1,250),list(1,500),list(250,500),list(500,500),list(500,250),list(500,1),list(250,1)))
		var/turf/boundary = locate(edge[1],edge[2],Z_LEVEL_VILTRUM)
		nexusSmokeAssert(istype(boundary,/turf/ViltrumOcean/Boundary), "Viltrum edge lacks the storm boundary")
		boundary_probe.Flying = FALSE
		boundary_probe.KB = FALSE
		nexusSmokeAssert(!boundary.Enter(boundary_probe), "Viltrum boundary allows walking")
		boundary_probe.Flying = TRUE
		nexusSmokeAssert(!boundary.Enter(boundary_probe), "Viltrum boundary allows flight")
		boundary_probe.KB = TRUE
		nexusSmokeAssert(!boundary.Enter(boundary_probe), "Viltrum boundary allows knockback")
		boundary_probe.SafeTeleport(boundary)
		nexusSmokeAssert(boundary_probe.loc == landing, "Viltrum boundary teleport did not return to the safe landing: [boundary_probe.x],[boundary_probe.y],[boundary_probe.z]")
	var/turf/normal_destination = locate(250,250,Z_LEVEL_VILTRUM)
	boundary_probe.SafeTeleport(normal_destination)
	nexusSmokeAssert(boundary_probe.loc == normal_destination, "Viltrum boundary guard changed a normal teleport")
	del(boundary_probe)

proc/runViltrumDoorStartupSmokeTests()
	// The palace/laboratory now use separate interiors. Exercise the reusable
	// grouped door animation on five temporary panels in a clear lab aisle.
	var/turf/door_position = locate(298,8,Z_LEVEL_CITY_INTERIORS)
	var/list/test_panels = list()
	for(var/tile_x = 296, tile_x <= 300, tile_x++)
		var/obj/ViltrumDoor/Laboratory/panel = new(locate(tile_x,8,Z_LEVEL_CITY_INTERIORS))
		panel.door_group = "nexus_smoke_lab_panels"
		test_panels += panel
	var/obj/ViltrumDoor/door = locate() in door_position
	nexusSmokeAssert(door && door.density && door.opacity && !door.Password, "Viltrum public door missing or incorrectly initialized")
	if(!door) return
	var/mob/NexusSmokeTest/door_probe = new(locate(298,7,Z_LEVEL_CITY_INTERIORS))
	nexusSmokeAssert(!door.Cross(door_probe) && door.density, "Viltrum door must remain dense during opening")
	sleep(4)
	var/list/panels = door.getDoorPanels()
	nexusSmokeAssert(panels.len == 5, "Viltrum door group must span five public entrance tiles")
	for(var/obj/ViltrumDoor/panel in panels)
		nexusSmokeAssert(!panel.density && !panel.opacity && panel.icon_state == "laboratory_open", "Viltrum grouped door did not finish opening")
	door_probe.SafeTeleport(door_position)
	door.Close()
	sleep(4)
	nexusSmokeAssert(!door.density && !door_probe.KO, "Viltrum public door closes on or harms its occupant")
	door_probe.SafeTeleport(locate(298,7,Z_LEVEL_CITY_INTERIORS))
	door.Close()
	sleep(4)
	nexusSmokeAssert(door.density && door.opacity && door.icon_state == "laboratory_closed", "Viltrum door did not close after its entrance cleared")
	del(door_probe)
	for(var/obj/ViltrumDoor/panel in test_panels) del(panel)
